# Generated by Django 6.0.1 on 2026-02-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
