# Generated by Django 6.0.1 on 2026-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
