# Generated by Django 6.0.1 on 2026-02-05 09:33

import ckeditor.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutCompany",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="company/image/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="company/logo/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Name & Logo",
                "verbose_name_plural": "Company Name & Logo",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(max_length=255, upload_to="company/social/"),
                ),
                ("link", models.URLField(max_length=255)),
            ],
            options={
                "verbose_name": "Company Social Media",
                "verbose_name_plural": "Company Social Media",
            },
        ),
        migrations.CreateModel(
            name="ContactDetail",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255)),
                (
                    "social_media",
                    models.ManyToManyField(blank=True, to="company.socialmedia"),
                ),
            ],
            options={
                "verbose_name": "Company Contact Detail",
                "verbose_name_plural": "Company Contact Details",
            },
        ),
        migrations.CreateModel(
            name="AboutCompanyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="company.aboutcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Information Translation",
                "db_table": "company_aboutcompany_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Name & Logo Translation",
                "db_table": "company_company_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
