# Generated by Django 6.0.1 on 2026-02-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.FileField(max_length=255, upload_to="company/socials/"),
        ),
    ]
