# Generated by Django 6.0.1 on 2026-02-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booktranslation",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
