# Generated by Django 6.0.1 on 2026-02-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_booktranslation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
