# Generated by Django 6.0.1 on 2026-02-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="in_stock",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Books count in stock"
            ),
        ),
    ]
