# Generated by Django 6.0.1 on 2026-03-11 12:10

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="gallery/covers/",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
                "ordering": ("order",),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="gallery/images/",
                    ),
                ),
                (
                    "original_video",
                    models.FileField(
                        blank=True,
                        help_text="Upload MP4/MOV/AVI. HLS will be generated automatically.",
                        max_length=500,
                        null=True,
                        upload_to="gallery/videos/originals/",
                    ),
                ),
                (
                    "hls_master_playlist",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="gallery/videos/hls/",
                        verbose_name="HLS Master Playlist (.m3u8)",
                    ),
                ),
                (
                    "hls_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="HLS Status",
                    ),
                ),
                (
                    "hls_error",
                    models.TextField(
                        blank=True,
                        help_text="Filled in if HLS conversion failed.",
                        null=True,
                        verbose_name="HLS Error",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gallery.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="GalleryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="gallery.gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Translation",
                "db_table": "gallery_gallery_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
